apiVersion: v1
kind: pod
metadata:
  name: result-app-pod
  lables:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
  image: dockersamples/examplevotingapp_result
  ports:
   containerPort: 80
