apiVersion: v1
kind: pod
metadata:
  name: voting-app-pod
  lables:
    name: voting-app-pod
    app: demo-voting-app
spec:
  conatners:
  - name: voting-app
  image: dockersamples/examplevotingapp_vote
  ports:
   containerPort: 80
